services:
  app:
    image: ghcr.io/fourtyfiver/stromabrechnung:latest
    user: "${UID:-1000}:${GID:-1000}"
    container_name: stromabrechnung
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always
